---
title: "0415的課"
author: "lianglinchia"
date: "4/19/2020"
output: html_document
---
```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```
```{r}
str(listExample)
```

```{r}
# 顯示到第一層


get1 <-listExample[["學期"]]
get2 <-listExample[["學期"]]
                   
```
```{r}
listExample[[1]]
listExample[[2]]
```
```{r}
get1$`108-1` -> get1_layer1
str(get1_layer1)
```
```{r}
get2 <-listExample["學期"]
get2_layer1 <- get2[[1]]
get2_layer2 <- get2_layer[["108-1"]]
get2_layer3 <- get2_layer2[[1]]
get2_layer3$teacher
```
```{r}
listExample["學期"][[1]][["108-1"]][[1]]$teacher
```
```{r}
today <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))
tomorrow <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))

weather <- list(today,tomorrow)

print(weather)
```
```{r}
weather[[1]][[2]][[2]] # 今天/新北市/highest_temp
weather[[2]][[2]][[2]] # 明天/新北市/highest_temp
```
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a
```
```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
a[[7]] <- "Johnson"

a <- c(a, c("Mary"))
```
```{r}
#ChangeDate
list1[[1]]$birthday <- ymd("1997-03-21")
list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```
```{r}
list1[[2]]$status <- c(height=163, weight=45)
list1[[1]]$status[["height"]] <- 176
str(list1)
```
```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)

# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)
```
```{r}
list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)

str(list1)
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```
```{r}
str(listExample)

# 108-1新增一科目成績
listExample$學期$`108-1`[[2]] <-
  list(name="產業經濟學")
str(listExample)

listExample$學期$`108-1`[[2]][c("teacher","grade")] <- 
  list(
    "Wen",
    88
    )
str(listExample)
```
```{r}
str(list1)
list1[[1]][-3] -> list1[[1]] # 小心回存的位置

list1[[2]][-c(4,5)] -> list1[[2]]
```
```{r}
str(list1)
list1[[2]][c(1,2)] <- NULL
str(list1)
```
```{r}
library(jsonlite)
fromJSON("https://data.ntpc.gov.tw/od/data/api/54DDDC93-589C-4858-9C95-18B2046CC1FC?$format=json", simplifyDataFrame = F) -> newTaipeiYouBike
```



