---
title: "0428"
author: "lianglinchia"
date: "4/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a <- c(2, 3, 5)
b <- c(4,-1, 3)
```


```{r}
a+b
a-b
```

```{r}
a%%b

a**b
```
```{r}
aaanum <- c(11, 6, 3)
print(aaanum)
aaanum%%2
```
```{r}
5*c(1,3,4)+7
```
```{r}
paste0(
  c("my name is"), c("XI","JingPing")
)
```
```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```
```{r}
str(example[c("name","height")])

pick_above170 <- example$height >= 170
example$name[pick_above170]
```
```{r}
source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")
```
```{r}
str(transcript100to103)
```
```{r}
table(transcript100to103$學屆)

table(transcript100to103$學屆[pick_above85])
```
```{r}
pick_above85 <-
  transcript100to103$`成績` > 85
```

```{r}
table(transcript100to103$學屆)

table(transcript100to103$學屆[pick_above85])
```
```{r}
print(example[c("name","birthday")])

pick_after98 <- example$birthday >=
lubridate::ymd("1998-01-01")
example$name[pick_after98]
```
```{r}
source("https://www.dropbox.com/s/16h6ggua6qtydci/exchangeRate.R?dl=1")
```
```{r}
str(exchangeRate)
```
```{r}
# 只要1998年1月（含）以後的
library(lubridate)
pick_after98_01 <-
  exchangeRate$期間 >= ymd("1998-01-01")
```
```{r}
exchangeRate_after98 <-
  list(
    `期間`=exchangeRate$`期間`[pick_after98_01],
    `幣別`=exchangeRate$`幣別`[pick_after98_01],
    `匯率`=exchangeRate$`匯率`[pick_after98_01]
  )
```
```{r}
print(example[c("name","allowance")])

pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
```
```{r}
example$allowance <- 
  ordered(example$allowance)
```
```{r}
pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
```
```{r}
example$allowance <-
  factor(
    example$allowance,
    levels=c("0-1000", "1001-2000", "2000+"),
    ordered = T # 設定為可排序factor
  )
```
```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/3uijub7xheib405/list_victimAges_female.json?dl=1", simplifyDataFrame = F) -> list_victimAges_female
```
```{r}
sum(list_victimAges_female$`數目`, na.rm=T)
```
```{r}
print(example[c("name","bloodType")])

pick_bloodB <- example$bloodType == "B"
example$name[pick_bloodB]
```
```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
pick_evens <- (sequenceNums %% 2) == 0
  sequenceNums[pick_evens]
sequenceNums %% 2
```
```{r}
x <- c(1,5,8)
y <- c(5,8)

# x裡的元素值是不是屬於y集合
x %in% y
```
```{r}

```


